# Trails in the Sky 1st Chapter (remake): facts from the Neoseeker walkthrough tables.
# Chest numbers follow the game's own count (212). Only facts: item names, floors, monster chests.
CHESTS = {
    1: ('Tear Balm', None, None),
    2: ('Thelas Balm', None, None),
    3: ('Small Box x2', None, None),
    4: ('Antidote x3', None, None),
    5: ('Tear Balm', None, None),
    6: ('Tear Balm', '2F', None),
    7: ('Dreamy Shell Bake', '3F', None),
    8: ("Monk's Staff", '3F', 'Wind Trapper x3'),
    9: ('EP Charge I', '3F', None),
    10: ('All Sepith x50', '4F', None),
    11: ('Green Sphere', '4F', 'Wind Trapper x3'),
    12: ('Droplet of Spirit', '5F', None),
    13: ('Curia Balm', '5F', None),
    14: ('Thelas Balm', '5F', None),
    15: ('EP Charge I', None, None),
    16: ('Droplet of Life', None, None),
    17: ('Thelas Balm', None, None),
    18: ('All Sepith x50', None, None),
    19: ('Mint Drop', None, None),
    20: ('Black Bangle', None, None),
    21: ('Droplet of Magic', None, None),
    22: ('Beast Hide Jumpsuit', None, None),
    23: ('EP Charge I', None, None),
    24: ('Droplet of Strength', None, None),
    25: ('All Sepith x50', None, None),
    26: ('Silver Earrings', None, None),
    27: ('Eye Drops x3', None, None),
    28: ('Laced Boots', None, 'Lily Mover+ x3, Lily Mover x3'),
    29: ('All Sepith x50', None, None),
    30: ('White Bracelet', None, None),
    31: ('Thelas Balm', None, None),
    32: ('Droplet of Defense', None, None),
    33: ('Tear Balm x3', None, None),
    34: ('EP Charge I x2', None, None),
    35: ('Pearl Earrings', None, None),
    36: ('Curia Balm x2', None, None),
    37: ('Katars', None, 'Rock Pecker+ x3, Rock Pecker x3'),
    38: ('All Sepith x100', None, None),
    39: ('Hit 2', None, None),
    40: ('Teara Balm', None, None),
    41: ('EP Charge II', None, None),
    42: ('Beast Steak', None, None),
    43: ('All Sepith x100', None, None),
    44: ('Mirage Ring', None, None),
    45: ('Droplet of Strength x2', None, None),
    46: ('U-Material', None, None),
    47: ('Strega R', None, 'Millipede Ball+ x2'),
    48: ('U-Material', None, None),
    49: ('Cursed Fried Eyeballs', None, None),
    50: ('Grail Ring', None, 'Wisdom+ x2'),
    51: ('Teara Balm', None, None),
    52: ('Flame Zippo', None, None),
    53: ('Thelas Balm x2', None, None),
    54: ('Cool Necklace', None, None),
    55: ('Droplet of Magic x2', None, None),
    56: ('Topaz Guard', '2F', None),
    57: ('Droplet of Defense x2', '2F', None),
    58: ('All Sepith x100', '4F', None),
    59: ('Yellow Sphere', '4F', 'Ground Trapper x3'),
    60: ('EP Charge II', '4F', None),
    61: ('Chain Mail', '4F', 'Ground Trapper x3'),
    62: ('Droplet of Spirit x2', '5F', None),
    63: ('Blind', '5F', None),
    64: ('EP Charge II', None, None),
    65: ('Glam Choker', None, None),
    66: ('Teara Balm', None, None),
    67: ('All Sepith x100', None, None),
    68: ('Teara Balm', 'B2F', None),
    69: ('EP Charge II', 'B2F', None),
    70: ('Scorpion', 'B2F', None),
    71: ('Thelas Balm x2', 'B2F', None),
    72: ('Bear Assault', 'B2F', None),
    73: ('Droplet of Life x2', 'B3F', None),
    74: ('U-Material', 'B3F', None),
    75: ('Chain Mail+', 'B3F', None),
    76: ('Strega R+', 'B3F', None),
    77: ('Jeweled Ring', 'B4F', None),
    78: ('Lily Necklace', None, None),
    79: ('Athelas Balm', None, None),
    80: ('Onyx Guard', None, None),
    81: ('Droplet of Defense x3', None, None),
    82: ('All Sepith x125', None, None),
    83: ('EP Charge II x2', None, None),
    84: ('Military Boots', None, 'Stove Plant+ , Stove Plant x6'),
    85: ('Droplet of Strength x3', None, None),
    86: ('Teara Balm x2', None, None),
    87: ('Droplet of Magic x3', None, None),
    88: ('U-Material x4', None, None),
    89: ('Skull Pendant', None, 'Sharkagator+ , Killer Shumock x2'),
    90: ('Zeram Powder', None, None),
    91: ('All Sepith x125', None, None),
    92: ('Break 2', None, None),
    93: ('Battle Suit', None, 'Flying Shrimp+ x3'),
    94: ('Freeze', None, None),
    95: ('U-Material x4', None, None),
    96: ('All Sepith x125', None, None),
    97: ('Scent', None, 'Gourd Boar+ , Mini Gourd Boars+ x3'),
    98: ('Droplet of Life x3', None, None),
    99: ('All Sepith x125', None, None),
    100: ('Droplet of Spirit x3', None, None),
    101: ('Golden Guard', None, None),
    102: ('Flamberge', '2F', 'Aqua Trapper x3'),
    103: ('Evade 2', '4F', None),
    104: ('EP Cut 2', '5F', None),
    105: ('Blue Sphere', '5F', 'Aqua Trapper x3'),
    106: ('Military Boots', '5F', None),
    107: ('Blazing Fried Chicken', '5F', None),
    108: ('Battle Suit', '5F', None),
    109: ('Tearal Balm', None, None),
    110: ('U-Material x3', None, None),
    111: ('All Sepith x150', None, None),
    112: ('EP Charge III', None, None),
    113: ('Droplet of Magic x4', None, None),
    114: ('Mute', None, None),
    115: ('Feather Brooch', None, None),
    116: ('EP Charge III', None, None),
    117: ('Deathblow', None, None),
    118: ('All Sepith x150', None, None),
    119: ('Zeram Capsule', None, None),
    120: ('G-Impact', None, 'White Pengu+ , Little Pengus+ Blue Pengu+ , Pink Pengu+'),
    121: ('Zeram Powder', None, None),
    122: ('Black Coat', None, 'Red Pengu+ , Yellow Pengu+ Green Pengu+ , Little Pengus+'),
    123: ('U-Material+', None, None),
    124: ('Athelas Balm', None, None),
    125: ('Tearal Balm', None, None),
    126: ('Droplet of Spirit x4', None, None),
    127: ('Athelas Balm', None, None),
    128: ('U-Material+', None, None),
    129: ('All Sepith x150', None, None),
    130: ('U-Material x3', None, None),
    131: ('Droplet of Strength x4', None, None),
    132: ('Tearal Balm', None, None),
    133: ('EP Charge III', None, None),
    134: ('Force Seal', None, None),
    135: ('Chaos Blade', None, 'Hopper Chief+ , Grass Hopper+ x3'),
    136: ('Octagonal Staff', None, 'Armored Rabbit+ x6'),
    137: ('Demi-Handers', None, 'Creepy Sheep+ x3'),
    138: ('U-Material+', '3F', None),
    139: ('Attack 3', '3F', None),
    140: ('Zanbato', '3F', 'Fire Trapper x3'),
    141: ('Zeram Powder', '4F', None),
    142: ('Red Sphere', '4F', 'Fire Trapper x3'),
    143: ('Black Coat', '5F', None),
    144: ('Infernal Fried Eggs', '5F', None),
    145: ('Mind 3', '5F', None),
    146: ('Droplet of Life x4', None, None),
    147: ('U-Material+', None, None),
    148: ('All Sepith x150', None, None),
    149: ('Zeram Powder', None, None),
    150: ('Droplet of Defense x4', None, None),
    151: ('Tearal Balm', None, None),
    152: ('EP Charge III', None, None),
    153: ('Elixir of Life', None, None),
    154: ('U-Material+ x2', None, None),
    155: ('Athelas Balm', None, None),
    156: ('All Sepith x200', None, None),
    157: ('Elixir of Strength', None, None),
    158: ('EP Cut 3', None, 'Crocoshark+ , Crocoshark x3'),
    159: ('EP 3', None, 'Dinedile+'),
    160: ('Chewy Spare Ribs', None, None),
    161: ('Cestus', None, None),
    162: ('Elixir of Magic', None, None),
    163: ('Reflector', None, None),
    164: ('U-Material+ x2', None, None),
    165: ('All Sepith x200', None, None),
    166: ('Proxy Puppet L', None, 'Dark Creepy Sheep+ Dark Creepy Sheep x6'),
    167: ('Hawkeye', None, None),
    168: ('Elixir of Defense', None, None),
    169: ('U-Material+ x2', None, None),
    170: ('All Sepith x200', None, None),
    171: ('Cloak', None, 'Whale Frog ♀+ , Whale Frog ♂+ x2'),
    172: ('Elixir of Spirit', None, None),
    173: ('Tearal Balm', None, None),
    174: ('Magester', None, 'Photon Judge+ , Broken Piece+ x2'),
    175: ('EP Charge III', None, None),
    176: ('Athelas Balm', None, None),
    177: ('Daedalus Arm', None, 'Guard Minion+ x5'),
    178: ('Royal Guard', None, None),
    179: ('Tear All Balm', None, None),
    180: ('Nine Tails', None, 'Doom Type S+ Doom Type D+ , Doom Type M+'),
    181: ('All Sepith x250', None, None),
    182: ('U-Material+ x3', None, None),
    183: ('Berserker', None, 'Broken Piece+ x2, Guard Minion+ x2'),
    184: ('EP Charge IV', None, None),
    185: ('All Sepith x250', None, None),
    186: ('Atlas Gear', None, None),
    187: ('Sylphen Boots', None, None),
    188: ('Hauteclaire', None, 'Photon Judge+ , Guard Minion+ x2'),
    189: ('Valkyrie Dress', None, None),
    190: ('U-Material+ x3', None, None),
    191: ('Athelas Balm EX', None, None),
    192: ("Thor's Hammer", None, 'Broken Piece+ , Broken Piece x3'),
    193: ('All Sepith x250', None, None),
    194: ('U-Material+ x3', None, None),
    195: ('Tear All Balm', None, None),
    196: ('Atlas Gear', None, None),
    197: ('EP Charge IV', None, None),
    198: ('Athelas Balm EX', None, None),
    199: ('Sylphen Boots', None, None),
    200: ('Tear All Balm', None, None),
    201: ('EP Charge IV', None, None),
    202: ('Athelas Balm EX', None, None),
    203: ('All Sepith x250', None, None),
    204: ('U-Material+ x3', None, None),
    205: ('Valkyrie Dress', None, 'Doom Type D+ , Broken Piece+ x2'),
    206: ('Erbe Blades', None, None),
    207: ('Tear All Balm', None, None),
    208: ('EP Charge IV', None, None),
    209: ('Arc Rod', None, 'Gandor+ , Doom Type S+ , Doom Type M+'),
    210: ('Athelas Balm EX', None, None),
    211: ('Royal Guard', None, None),
    212: ('Zeram Capsule', None, None),
}
