# Portuguese for Welcome to Elderfield tasks (our own translation; see wte_pt.py), plus our own
# English wording for rewards the guide described in its own words.

TASK_NAMES = {
    'Casting Your Line': 'Lançando a Linha', "The Farmer's Path": 'O Caminho do Fazendeiro', 'Helping Molly': 'Ajudando a Molly',
    'A Snack for a Cat': 'Um Petisco para o Gato', 'The Dusklight Pearls': 'As Pérolas do Crepúsculo', 'A Herbal Cure': 'Uma Cura de Ervas',
    'Stocking the Storehouse': 'Abastecendo o Depósito', 'Mysteries of the Deep Woods': 'Mistérios da Floresta Profunda',
    'A Strange Elixir': 'Um Elixir Estranho', 'Lost Journal': 'Diário Perdido', 'Lost Pocket Knife': 'Canivete Perdido',
    'Dental Records': 'Arcada Dentária', 'Silver and Bone': 'Prata e Osso', 'The Coins of Death': 'As Moedas da Morte',
    'Supply Run': 'Busca de Suprimentos', 'Missing Skeletons': 'Esqueletos Desaparecidos', 'An Adventurous Spirit': 'Um Espírito Aventureiro',
    'Cursed Cuisine': 'Cozinha Amaldiçoada', 'Good as Gold': 'Vale Ouro', 'Lost Supplies': 'Suprimentos Perdidos',
    'Skeletal Survey': 'Levantamento Esquelético', 'Secrets of the Catacombs': 'Segredos das Catacumbas', 'Feed the Mold': 'Alimente o Mofo',
    'Farming Supplies': 'Suprimentos de Fazenda', 'False Idols': 'Falsos Ídolos', 'Hidden Shrines': 'Santuários Escondidos',
    'Forbidden Snack': 'Lanche Proibido', 'Skeletal Depths': 'Profundezas Esqueléticas', 'The Strange Orb': 'O Orbe Estranho',
    'Shopper-Bopper!': 'Caça ao Consumidor!', 'Babysitting...?': 'Babá...?', 'An Eldritch Prank': 'Uma Pegadinha Sobrenatural',
    'Build-A-Wife': 'Monte uma Esposa', 'Parks and Recreation': 'Parques e Recreação', 'Time to Investigate': 'Hora de Investigar',
    "Skelekid's Tasks": 'Tarefas do Skelekid', 'Fishing in the Mall...?': 'Pescando no Shopping...?', 'By the Gods': 'Pelos Deuses',
    'Artwork for Abigail': 'Uma Obra para a Abigail', 'Healthy Eating': 'Comendo Bem', 'Laundry Day': 'Dia de Lavar Roupa',
    "A Bit o' Fishin'": 'Uma Pescariazinha', 'Bug Catching': 'Caçando Insetos', 'An Unusual Catch': 'Uma Pesca Incomum',
    'Helping Grandma': 'Ajudando a Vovó', 'Penpals': 'Amigos por Correspondência', 'Secrets of the Deep': 'Segredos das Profundezas',
    'The Mycologist': 'A Micóloga', 'Sweet and Sour': 'Agridoce', 'Deer Season': 'Temporada de Cervos',
    'A Balanced Breakfast': 'Um Café da Manhã Equilibrado', 'Artisanal Goods': 'Produtos Artesanais', 'Childhood Fear': 'Medo de Infância',
    'A Ghostly Catch': 'Uma Pesca Fantasmagórica', 'The Best Medicine': 'O Melhor Remédio', 'A Filling Meal': 'Uma Refeição Farta',
    'Redecorating': 'Redecorando', 'A Fancy Drink': 'Uma Bebida Chique', 'Cryptic Crystals': 'Cristais Enigmáticos',
    'The Gatekeeper': 'O Guardião do Portão', 'Tentacle Cleanup': 'Limpeza de Tentáculos', 'The Skull Chalice': 'O Cálice de Crânio',
    'A Fast Food Fiend': 'Um Viciado em Fast Food', 'The Local Joggers Club': 'O Clube de Corrida Local',
    'Tree Branch Cleanup': 'Limpeza de Galhos', 'Meet Sophia': 'Conheça a Sophia', 'Bone Cleanup': 'Limpeza de Ossos',
}

# Objectives, rewards and task locations: English as the guide has it → Portuguese.
LINES = {
    'Bring Herb a Ghost Flounder': 'Leve um Linguado Fantasma ao Herb',
    'Bring Herb a Fog Eel': 'Leve uma Enguia da Névoa ao Herb',
    'Grow and harvest a single Wheat crop': 'Plante e colha um pé de Trigo',
    'The respect of Farmer Hans..?': 'O respeito do Fazendeiro Hans..?',
    'Bring Molly a Copper Ore': 'Leve um Minério de Cobre à Molly',
    "Access to Molly's workshop": 'Acesso à oficina da Molly',
    'Bring Dave a Fog Broth': 'Leve um Caldo de Névoa ao Dave',
    'A Preserving Barrel': 'Um Barril de Conserva',
    'Pearls found: (3 required)': 'Pérolas encontradas: (3 necessárias)',
    'A "special axe" of some kind': 'Algum tipo de "machado especial"',
    'Bring Grace a Herbal Salve': 'Leve uma Pomada de Ervas à Grace',
    'A Golden Hatchet': 'Uma Machadinha Dourada',
    'Restock the Storehouse': 'Reabasteça o depósito',
    'Mysteries Investigated: (3 required)': 'Mistérios investigados: (3 necessários)',
    'Bring Samson a Soulbargain Potion': 'Leve uma Poção do Pacto de Alma ao Samson',
    "Find Jacob's Lost Journal": 'Encontre o diário perdido do Jacob',
    "Find Sarah's Lost Pocket Knife": 'Encontre o canivete perdido da Sarah',
    'Find 5 Golden Teeth': 'Encontre 5 Dentes de Ouro',
    'A key to one of the gates': 'A chave de um dos portões',
    'Craft a Necklace of Bone': 'Crie um Colar de Osso',
    'Find all four Gold Coins of Death': 'Encontre as quatro Moedas de Ouro da Morte',
    'The Final Key': 'A Chave Final',
    'Bring Lydia a Herbal Stew, Herbal Feast, Herbal Serpent and Herbal Roast':
        'Leve à Lydia um Ensopado de Ervas, um Banquete de Ervas, uma Serpente com Ervas e um Assado com Ervas',
    'Find Dimitri in the tunnels': 'Encontre o Dimitri nos túneis',
    'Mysteries investigated: (5 required)': 'Mistérios investigados: (5 necessários)',
    'Mysteries investigated: (8 required)': 'Mistérios investigados: (8 necessários)',
    'Mysteries investigated: (3 required)': 'Mistérios investigados: (3 necessários)',
    'Mysteries investigated: (6 required)': 'Mistérios investigados: (6 necessários)',
    'Mysteries investigated: (7 required)': 'Mistérios investigados: (7 necessários)',
    'Mysteries investigated': 'Mistérios investigados',
    '...Something, maybe?': 'Talvez... alguma coisa?',
    'Cook a Stew of Six Curses': 'Cozinhe um Ensopado das Seis Maldições',
    'A new cooking recipe': 'Uma receita nova',
    'Catch a Golden Beetle': 'Capture um Besouro Dourado',
    'Woodworking knowledge of some kind': 'Algum conhecimento de marcenaria',
    'Supplies found: (3 required)': 'Suprimentos encontrados: (3 necessários)',
    "Find Jess's Lost Notes": 'Encontre as anotações perdidas da Jess',
    'A Small Hammer or two., One final prize': 'Um ou dois Martelos Pequenos e um último prêmio',
    'Bring 10 Living Bones to Carlos': 'Leve 10 Ossos Vivos ao Carlos',
    'A way to pass through the Hardened Bones': 'Um jeito de atravessar os Ossos Endurecidos',
    'Bring Farmer Sven 10 Dense Fertilizer (Lv2) and 10 Fancy Fertilizer (Lv2)':
        'Leve ao Fazendeiro Sven 10 Fertilizantes Densos (Nv2) e 10 Fertilizantes Refinados (Nv2)',
    'Access to a new type of crop': 'Acesso a um novo tipo de cultivo',
    'Craft a Kaal Idol and bring it to Denzel': 'Crie um Ídolo de Kaal e leve ao Denzel',
    'Shrines found: (2 required)': 'Santuários encontrados: (2 necessários)',
    'Cook a Forbidden Snack': 'Cozinhe um Lanche Proibido',
    'Reach the 2nd floor of the Catacombs Mines': 'Chegue ao 2º andar das Minas das Catacumbas',
    'A Large Hammer': 'Um Martelo Grande',
    'Obtain the skull of... something': 'Consiga o crânio de... alguma coisa',
    'The key to the Catacombs Mine gate': 'A chave do portão da Mina das Catacumbas',
    'Find and defeat a Shopper at the mall': 'Encontre e derrote um Consumidor no shopping',
    'Find Ben': 'Encontre o Ben',
    'Parents Slimed': 'Pais engosmados',
    'Wife-building progress: (5 required)': 'Progresso da esposa: (5 necessários)',
    '"Dark Magic" of some kind.': 'Algum tipo de "magia sombria".',
    'Talk to the Manager': 'Fale com o gerente',
    'Find the Wand of Parks and Recreation for Manager John': 'Encontre a Varinha de Parques e Recreação para o gerente John',
    'Slay Drippers (5 required)': 'Derrote Gotejadores (5 necessários)',
    'Slay Pipe Cleaners: (5 required)': 'Derrote Limpa-canos: (5 necessários)',
    'Bring the Office Worker a Stalktopus': 'Leve um Polvo-de-antenas ao funcionário do escritório',
    "They'll call the Mall Administrator for us, hopefully.": 'O Administrador do Shopping é chamado',
    'God Shrines investigated: (2 required)': 'Santuários dos deuses investigados: (2 necessários)',
    'The secrets of the shrine.': 'Os segredos do santuário',
    'Find a local artist': 'Encontre um artista local',
    'Bring Ellie a Mana Muffin in exchange for her masterpiece': 'Leve um Muffin de Mana à Ellie em troca da obra-prima dela',
    "Bring Ellie's Artwork to Abigail and claim your reward": 'Leve a obra da Ellie à Abigail e pegue sua recompensa',
    'Some rare seeds': 'Algumas sementes raras',
    'Bring Jeremiah a Light Salad': 'Leve uma Salada Leve ao Jeremiah',
    "Find Tracy's Laundry": 'Encontre a roupa da Tracy',
    'Bring Herb a Razorfish': 'Leve um Peixe-navalha ao Herb',
    'Bring Herb a Gold quality or higher Ancient Pike': 'Leve ao Herb um Lúcio Ancestral de qualidade Ouro ou melhor',
    'Bring Hans a Pale Empress Moth': 'Leve uma Mariposa Imperatriz Pálida ao Hans',
    'Unlock Gloom Hops Seeds': 'Libera a Semente de Lúpulo Sombrio',
    'Bring Herb a Bonefish': 'Leve um Peixe-osso ao Herb',
    'Bring Herb an Ancient Manta': 'Leve uma Manta Ancestral ao Herb',
    'Acquire a Palewood Branch': 'Consiga um Galho de Madeira Pálida',
    "Grandma's forgiveness": 'O perdão da Vovó',
    'Speak to Brittany for more details': 'Fale com a Brittany para saber mais',
    'Speak to Carla': 'Fale com a Carla',
    'Unlocks Bean Seeds': 'Libera a Semente de Feijão',
    'Speak to Art for more details': 'Fale com o Art para saber mais',
    'Reach the third floor of the Mall Mines': 'Chegue ao 3º andar das Minas do Shopping',
    'Blueprint: Preserving Barrel': 'Projeto: Barril de Conserva',
    'Speak to Isabella for more details': 'Fale com a Isabella para saber mais',
    'Find a Giant Mushroom': 'Encontre um Cogumelo Gigante',
    "Access to Isabella's lab": 'Acesso ao laboratório da Isabella',
    'Speak to Juan for more details': 'Fale com o Juan para saber mais',
    'Find a jar of Honey and a Golden Mushroom': 'Encontre um pote de Mel e um Cogumelo Dourado',
    'An old family recipe': 'Uma receita antiga de família',
    'Find a Deer Claw': 'Encontre uma Garra de Cervo',
    'A special recipe to make use of deer meat': 'Uma receita especial para usar carne de cervo',
    'Speak to Terry for more details': 'Fale com o Terry para saber mais',
    'Bring a Mayonnaise and Cheese to Terry': 'Leve Maionese e Queijo ao Terry',
    'The secret to a balanced breakfast': 'O segredo de um café da manhã equilibrado',
    'Speak to Damian for more details': 'Fale com o Damian para saber mais',
    'Bring Damian a Jelly (Bloodberry) and Pickles (Radish)': 'Leve ao Damian uma Geleia (Baga-de-sangue) e uma Conserva (Rabanete)',
    'Some old recipe books': 'Alguns livros de receitas antigos',
    'Speak to Dan at the local store': 'Fale com o Dan na loja local',
    "Investigate Dan's story at Greystone Estates": 'Investigue a história do Dan no Residencial Greystone',
    "Find Sam's Lucky Pendant": 'Encontre o pingente da sorte do Sam',
    'Meet Sam in the stairwell to clear the rubble': 'Encontre o Sam na escada para tirar os escombros',
    'Offer 10 Spiritwood and 10 Leather at the Greystone altar': 'Ofereça 10 Madeiras Espirituais e 10 Couros no altar do Greystone',
    'Tell Dan about your findings': 'Conte ao Dan o que você descobriu',
    'Unlock a new seed type': 'Libera um novo tipo de semente',
    'Speak to Trisha for more details': 'Fale com a Trisha para saber mais',
    'Bring Trisha a Gold quality or higher Ghost Flounder': 'Leve à Trisha um Linguado Fantasma de qualidade Ouro ou melhor',
    'A Lightning Rod blueprint': 'Um projeto de Para-raios',
    'Speak to Zoe in the Library': 'Fale com a Zoe na Biblioteca',
    'Bring Zoe a Bone Honey': 'Leve um Mel de Osso à Zoe',
    'Unlock Strawberry Seeds': 'Libera a Semente de Morango',
    'Speak to Daryl in the Pet Shop': 'Fale com o Daryl no Pet Shop',
    'Bring Daryl a Filling Platter': 'Leve uma Travessa Farta ao Daryl',
    'Unlock Cauliflower Seeds': 'Libera a Semente de Couve-flor',
    'Speak to Jeannie in Greystone Estates room #10': 'Fale com a Jeannie no quarto 10 do Residencial Greystone',
    'Bring 25 Ancientwood and a Greater Deep Crystal to Jeannie': 'Leve 25 Madeiras Ancestrais e um Cristal das Profundezas Maior à Jeannie',
    "Some of Jeannie's old furniture": 'Alguns móveis antigos da Jeannie',
    'Speak to Earl in Greystone Estates room #2': 'Fale com o Earl no quarto 2 do Residencial Greystone',
    'Bring Earl any type of Duskberry Wine': 'Leve ao Earl qualquer Vinho de Baga-do-crepúsculo',
    'Some "weird stuff" from the basement...': 'Umas "coisas esquisitas" do porão...',
    'Speak to Art for more information': 'Fale com o Art para saber mais',
    'Bring Art a set of all 6 basic Elemental Crystals': 'Leve ao Art um conjunto dos 6 Cristais Elementais básicos',
    'Bring Art a set of all 6 greater Elemental Crystals': 'Leve ao Art um conjunto dos 6 Cristais Elementais maiores',
    'Bring the Gatekeeper some pizza': 'Leve pizza ao Guardião do Portão',
    'Find the first Gate Key': 'Encontre a primeira Chave do Portão',
    'Speak to the Gatekeeper': 'Fale com o Guardião do Portão',
    'Find the second Gate Key': 'Encontre a segunda Chave do Portão',
    'Find the final Gate Key': 'Encontre a última Chave do Portão',
    'Sort out this tentacle mess': 'Dê um jeito nessa bagunça de tentáculos',
    'Craft a Skull Chalice at a workbench': 'Crie um Cálice de Crânio na bancada',
    'The ability to grow Pumpkins': 'Poder plantar Abóboras',
    'Defeat the Denizen of the Deep Fryer in the mall food court': 'Derrote o Morador da Fritadeira na praça de alimentação do shopping',
    'A new type of seed': 'Um novo tipo de semente',
    'Speak to Barry at The Local Joggers Club': 'Fale com o Barry no Clube de Corrida Local',
    'Find the Mill Key somewhere in The Old Woods': 'Encontre a Chave do Moinho em algum lugar do Bosque Antigo',
    'Reclaim the Lost Mirror from the Abandoned Mill': 'Recupere o Espelho Perdido no Moinho Abandonado',
    'Bring the Lost Mirror to Barry in the Local Joggers Club': 'Leve o Espelho Perdido ao Barry no Clube de Corrida Local',
    "Tell Michelle that you've been accepted into The Local Joggers Club": 'Conte à Michelle que você entrou no Clube de Corrida Local',
    'Bring Michelle a single Verdite Ore': 'Leve um Minério de Verdite à Michelle',
    'The secrets of the Local Joggers Club': 'Os segredos do Clube de Corrida Local',
    'Sort out this tree branch mess': 'Dê um jeito nessa bagunça de galhos',
    'Speak to Charlie on the 3rd floor': 'Fale com o Charlie no 3º andar',
    'Place the doll near the pit on the 3rd floor': 'Coloque a boneca perto do buraco no 3º andar',
    'Unlocks Coffee Bean Seeds': 'Libera a Semente de Grão de Café',
    'Sort out this bone mess': 'Dê um jeito nessa bagunça de ossos',
    'At this point... who cares?': 'A essa altura... quem se importa?',
    # Task locations
    'Town - Lakefront': 'Cidade - Beira do Lago', 'Farmhouse': 'Casa da Fazenda', 'Farm Path': 'Caminho da Fazenda', 'Town': 'Cidade',
    'Deep Woods Village': 'Vila da Floresta Profunda', 'Deep Woods': 'Floresta Profunda', 'Deep Catacombs': 'Catacumbas Profundas',
    'The Old Woods - Campsite': 'Bosque Antigo - Acampamento', 'The Old Woods': 'Bosque Antigo', 'The Catacombs 2F': 'Catacumbas 2º andar',
    'Sealed Chamber': 'Câmara Selada', 'The Catacombs 3F': 'Catacumbas 3º andar', 'The Forsaken Settlement': 'O Povoado Abandonado',
    'Town - Park': 'Cidade - Parque', 'Music Store': 'Loja de Música', 'Mall Back office': 'Escritório dos fundos do Shopping',
    'House Basement': 'Porão da casa', 'Sewers (North East)': 'Esgotos (Nordeste)', 'Greystone Estates Room 6': 'Residencial Greystone, quarto 6',
    "Grandma's Cabin": 'Cabana da Vovó', 'Town (North)': 'Cidade (Norte)', 'Town (Saloon)': 'Cidade (Saloon)',
    "Town (Jogger's Club)": 'Cidade (Clube de Corrida)', 'Town (Carpenter)': 'Cidade (Carpintaria)', 'Town (Store)': 'Cidade (Loja)',
    'Town - Abandoned Building': 'Cidade - Prédio Abandonado', 'Town (Library)': 'Cidade (Biblioteca)', 'Town (Pet Shop)': 'Cidade (Pet Shop)',
    'Greystone Estates': 'Residencial Greystone', 'Greystone Estates (Room #2)': 'Residencial Greystone (quarto 2)',
    'Town (North-East)': 'Cidade (Nordeste)', 'Sewers F1': 'Esgotos 1º andar',
}

# Rewards the guide wrote in its own voice, reworded in ours.
REWARD_EN = {
    "They'll call the Mall Administrator for us, hopefully.": 'The Mall Administrator gets called',
    'At this point... who cares?': 'Nothing in particular',
    'A Small Hammer or two., One final prize': 'One or two Small Hammers, and a final prize',
}
LINES['At this point... who cares?'] = 'Nada em especial'

# Treasure maps in our own words: (how to get it, where to dig), English and Portuguese.
MAPS = {
    1: (('Talk to the cat in the farmhouse.', 'Converse com o gato na casa da fazenda.'),
        ('Mall parking lot, by the big tree between the lot and the entrance.', 'Estacionamento do shopping, junto à árvore grande entre o estacionamento e a entrada.')),
    2: (('Lend Ellie some money while she shops in the General Store.', 'Empreste dinheiro à Ellie quando ela estiver comprando no Armazém.'),
        ("Sewers: right of the god shrine behind a Gatekeeper's door, below the drain.", 'Esgotos: à direita do santuário atrás de uma porta do Guardião, abaixo do ralo.')),
    3: (('Talk to Alice.', 'Converse com a Alice.'),
        ("Ranch, under the streetlamp next to Klaus's house.", 'Rancho, embaixo do poste ao lado da casa do Klaus.')),
    4: (('Random: the pentagram mystery in the Parks and Recreation office.', 'Aleatório: o mistério do pentagrama no escritório de Parques e Recreação.'),
        ('Lakefront, just right of the tree beside the picnic table, above the life buoy.', 'Beira do Lago, logo à direita da árvore ao lado da mesa de piquenique, acima da boia.')),
    5: (('Random: tier 1 book loot in the Mall Mines.', 'Aleatório: livros (nível 1) achados nas Minas do Shopping.'),
        ('Mall back offices, by the Stalktopus pond, just below the clock across the pond.', 'Escritórios dos fundos do shopping, no lago do Polvo-de-antenas, logo abaixo do relógio do outro lado.')),
    6: (('Talk to Molly in her workshop.', 'Converse com a Molly na oficina dela.'),
        ('Mall, left of the mines entrance, next to the blue trash can.', 'Shopping, à esquerda da entrada das minas, ao lado da lixeira azul.')),
    7: (('Talk to Celeste.', 'Converse com a Celeste.'),
        ('North-west of town, north of the church: right of the big tree by the water tower with the eye.', 'Noroeste da cidade, ao norte da igreja: à direita da árvore grande perto da caixa d’água com o olho.')),
    8: (('Gossip with Blorph.', 'Fofoque com o Blorph.'), ('Park, below the seesaw.', 'Parque, abaixo da gangorra.')),
    9: (('Fishing treasure.', 'Tesouro de pesca.'), None),
    10: (('Fishing treasure.', 'Tesouro de pesca.'), None),
    11: (('Talk to Alice while she is at the farmhouse.', 'Converse com a Alice quando ela estiver na casa da fazenda.'),
         ("Mall Music Store, in front of the three brown guitars on the back wall.", 'Loja de Música do shopping, na frente das três guitarras marrons da parede do fundo.')),
    12: (('Talk to Josh in the Art Gallery.', 'Converse com o Josh na Galeria de Arte.'),
         ('Sewers next to Greystone Estates, behind the door that needs the Slimy Key.', 'Esgotos ao lado do Residencial Greystone, atrás da porta que pede a Chave Gosmenta.')),
}

# How each recipe becomes available ("unlock"), English as the wiki has it → our Portuguese.
UNLOCKS = {
    'Automatically available with workbench': 'Disponível desde o início na bancada',
    'Automatically available at the Forge': 'Disponível desde o início na forja',
    "Automatically available with Craftsman's Bench": 'Disponível desde o início na Bancada do Artesão',
    'Requires Forge Upgrade (t2)': 'Precisa da Melhoria da Forja (n2)',
    'Automatically available with Potion Lab': 'Disponível desde o início no Laboratório de Poções',
    'Automatically available with Prep Table': 'Disponível desde o início na Mesa de Preparo',
    'Automatically available with Witching Mortar': 'Disponível desde o início no Pilão de Bruxaria',
    'Automatically available with Compost Bin': 'Disponível desde o início na Composteira',
    'Aligned to the God Daeus': 'Ligado ao deus Daeus', 'Aligned to the God Delvek': 'Ligado ao deus Delvek',
    'Aligned to the God Valtris': 'Ligado ao deus Valtris', 'Aligned to the God Hagroth': 'Ligado ao deus Hagroth',
    'Aligned to the God Nezroth': 'Ligado ao deus Nezroth', 'Aligned to the God Gatis': 'Ligado ao deus Gatis',
    "Blueprint: Automatically available with Tinker's Desk": 'Projeto: disponível desde o início na Mesa do Inventor',
    "Blueprint: Automatically available with Tinker's Desk|-": 'Projeto: disponível desde o início na Mesa do Inventor',
    'Recipe: Purchased from Chef Elroy after building house upgrade 1': 'Receita: compre do Chef Elroy depois da melhoria 1 da casa',
    "Blueprint: Purchased from Henrietta's shop": 'Projeto: compre na loja da Henrietta',
    'Basic beginner recipe Place in fridge or inventory to use for other recipes': 'Receita inicial. Guarde na geladeira ou no inventário para usar em outras receitas',
    'Basic beginner recipe Purchase from Saloon': 'Receita inicial. Compre no Saloon',
    'Recipe: from Fisherman Herb after completing stage 1 of "Casting your line" task': 'Receita: do Pescador Herb depois da etapa 1 de "Lançando a Linha"',
    'Recipe: purchased from Chef Elroy after completing "The Skull Chalice" task': 'Receita: compre do Chef Elroy depois de "O Cálice de Crânio"',
    'Recipe: purchased from Chef Elroy after completing "A Fast Food Fiend" task': 'Receita: compre do Chef Elroy depois de "Um Viciado em Fast Food"',
    'Basic beginner recipe': 'Receita inicial',
    'Recipe: Purchased from the Saloon shop': 'Receita: compre na loja do Saloon',
    'Recipe: Purchased from Chef Elroy after building house upgrade 1 and Defeating the Ancient Tree':
        'Receita: compre do Chef Elroy depois da melhoria 1 da casa e de derrotar a Árvore Ancestral',
    'Reward for completing the "Artisanal Goods" job board task': 'Recompensa da tarefa do quadro "Produtos Artesanais"',
    'Automatically available with workbench A gift after completing Farmer Hans tasks "The Farmer\'s Path"':
        'Disponível desde o início na bancada. Também é presente do Fazendeiro Hans depois de "O Caminho do Fazendeiro"',
    'Molly gifts you one & unlocks the blueprint after you\'ve completed her "Helping Molly" tasks & her get back into the Workshop':
        'A Molly dá um e libera o projeto depois de "Ajudando a Molly", quando ela volta para a oficina',
    'Completing Dave\'s tasks: "A snack for a cat" gives a Preserving Barrel Blueprint: Completing Art\'s tasks: "Secrets of the Deep"':
        '"Um Petisco para o Gato" (Dave) dá um Barril de Conserva; o projeto vem de "Segredos das Profundezas" (Art)',
    'Completing Hank\'s tasks: "Good As Gold" gives blueprint': '"Vale Ouro" (Hank) dá o projeto',
    'Completing Trisha\'s tasks: "A Ghostly Catch" gives blueprint': '"Uma Pesca Fantasmagórica" (Trisha) dá o projeto',
    'Blueprint: Completing Molly\'s task: "The Elder Gem"': 'Projeto: tarefa "A Gema Anciã" da Molly',
    'Blueprint: Building the Basement and opening the box in it': 'Projeto: construa o porão e abra a caixa que está nele',
    'Blueprint: Given by Herb after completing "A Bit o\' Fishin\'" task': 'Projeto: o Herb dá depois de "Uma Pescariazinha"',
    'Blueprint: Starting Farmer Hans\' tasks: "The Skull Chalice"': 'Projeto: ao começar "O Cálice de Crânio" (Fazendeiro Hans)',
    'Blueprint: Starting Denzel\'s tasks: "False Idols"': 'Projeto: ao começar "Falsos Ídolos" (Denzel)',
    'Blueprint: Winning the "Egg" Festival': 'Projeto: vencendo o Festival do Ovo',
    'Blueprint: Dropped from the Cornstalker on the Farm': 'Projeto: cai do Espreita-milho na fazenda',
    'Blueprint: Getting Very Highly Appreciated in the Harvest Festival': 'Projeto: tirando a nota mais alta no Festival da Colheita',
    'Recipe: Complete the task "Farming Supplies"': 'Receita: conclua "Suprimentos de Fazenda"',
    'Basic beginner recipe Place in fridge or inventory to use for other recipes Place in chest or inventory to use for crafting ingredient':
        'Receita inicial. Guarde na geladeira, num baú ou no inventário para usar em outras receitas',
    'Recipe: from Fisherman Herb after completing stage 2 of "Casting your line" task Purchase from Saloon':
        'Receita: do Pescador Herb depois da etapa 2 de "Lançando a Linha", ou compre no Saloon',
    'Recipe: A gift from Edwin after he tells you that he is an amateur chef, while he takes a walk by the General Store':
        'Receita: presente do Edwin quando ele conta que é chef amador, passeando perto do Armazém',
    'Recipe: purchased from Chef Elroy after completing "A Fast Food Fiend" task Place in fridge or inventory to use for other recipes':
        'Receita: compre do Chef Elroy depois de "Um Viciado em Fast Food"',
    'Recipe: purchase from Chef Elroy': 'Receita: compre do Chef Elroy',
    'Recipe: Mall Mines (book on the ground)': 'Receita: livro no chão das Minas do Shopping',
    'Recipe: from Fisherman Herb after completing stage 2 of "Casting your line" task': 'Receita: do Pescador Herb depois da etapa 2 de "Lançando a Linha"',
    'Recipe: From Edwin as he takes a walk near the Notice Board': 'Receita: do Edwin, passeando perto do quadro de avisos',
    'Recipe: after defeating the Flesh Girl in Greystone Estates': 'Receita: depois de derrotar a Garota de Carne no Residencial Greystone',
    'Reward for completing the "Deer Season" Job Board Task': 'Recompensa da tarefa do quadro "Temporada de Cervos"',
    'Recipe: Given by Herb after completing "A Bit o\' Fishin\'" task': 'Receita: o Herb dá depois de "Uma Pescariazinha"',
    'Recipe: from Fisherman Herb after completing the task to bring him a Razorfish': 'Receita: do Pescador Herb depois de levar um Peixe-navalha a ele',
    'Recipe: by completing the "Cursed Cuisine" Task for Gretta': 'Receita: conclua "Cozinha Amaldiçoada" (Gretta)',
    'Reward for completing the "Sweet and Sour" job board task': 'Recompensa da tarefa do quadro "Agridoce"',
    'Recipe: Given by the Chef in the Old Woods Campsite': 'Receita: o Chef dá no Acampamento do Bosque Antigo',
    'Recipe: Given by the Chef outside the Old Woods Mines': 'Receita: o Chef dá na entrada das Minas do Bosque Antigo',
    'Recipe: Given by the chef in the Library': 'Receita: o Chef dá na Biblioteca',
    'Recipe: Given by the Chef in the Library': 'Receita: o Chef dá na Biblioteca',
    'Recipe: Treasure Map 3 Purchase from The Garbage Man Mondays & Thursdays (occasionally)':
        'Receita: Mapa do Tesouro 3, ou compre do Homem do Lixo às segundas e quintas (às vezes)',
    'Recipe: Given by Gretta for the task "Cursed Cuisine"': 'Receita: a Gretta dá em "Cozinha Amaldiçoada"',
    'Recipe: Given by Zeek for the task "Forbidden Snack"': 'Receita: o Zeek dá em "Lanche Proibido"',
    'Recipe: basic oven recipe': 'Receita: receita básica de forno',
    'Automatically available at the Forge. /': 'Disponível desde o início na forja',
    'Requires Forge Upgrade (t2) /': 'Precisa da Melhoria da Forja (n2)',
}
